<?php

/*
Template Name: searchPage
*/
get_header();
?>

<div id="content-anchor" class="site-content small-12">
    <section id="content" class="module" data-ng-controller="ContentController">
        <div class="module__content">
            <section data-widget-catalog data-widget-container data-widget-id="9" data-widget-sort="" data-widget-url="/widget?isDomain=1&amp;searchQuery=&amp;route=productSearchNew&amp;on_main=0&amp;type=11&amp;widget_id=9" data-region="" data-widget-type="11" class=" widget-block block-9">


                <section id="products" data-block-id="9" class=" catalog-search-results catalog widget on-view widget-block">
                    <br><br><br><br>
                    <header class="widget__header text-center widget__header_underlined row">
                        <div class="small-12 column">
                            <h1>Каталог товаров</h1>
                        </div>
                    </header>
                    <div class="content-block widget__content widget__content_filled" id="products-show">
                        <div class="row widget__inner">
                            <div data-ng-non-bindable class="column small-12 large-12">
                                <div class="catalog__search">

                                    <section id="catalogsearch" data-block-id="14" class="
         catalog-search -nt-widget widget widget-block row"><article class="small-12 column"><form method="GET" action="/products/search">
                                                <input type="hidden" name="sort" value="0"><input type="hidden" name="balance" value=""><input type="hidden" name="categoryId" value=""><input type="hidden" name="min_cost" value=""><input type="hidden" name="max_cost" value=""><input type="hidden" name="page" value="1"><div class="row"><div class="input-group">
                                                        <div class="input-group__field"><input type="text" class="catalog-search__input input-group__input" placeholder="Поиск по каталогу" name="text" value=""></div>
                                                        <div class="input-group__button "><button class="button catalog-search__button button_for_search large-12"><span class="button__icon svg-icon svg-icon_smallx"><!-- Generated by IcoMoon.io --><svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="768" height="768" viewbox="0 0 768 768"><g id="icomoon-ignore"></g><path d="M304.5 448.5c79.5 0 144-64.5 144-144s-64.5-144-144-144-144 64.5-144 144 64.5 144 144 144zM496.5 448.5l159 159-48 48-159-159v-25.5l-9-9c-36 31.5-84 49.5-135 49.5-115.5 0-208.5-91.5-208.5-207s93-208.5 208.5-208.5 207 93 207 208.5c0 51-18 99-49.5 135l9 9h25.5z"></path></svg></span><span class="button__text show-for-large">Найти</span></button></div>
                                                    </div></div>
                                            </form></article></section>

                                </div>
                                <div class="small-12">

                                </div>
                                <div class="hide-for-large">

                                </div>



                                <article class="row small-up-2 medium-up-3 large-up-4 catalog__list"><div class="catalog__product column"><div class="product-item product-item_250x190  text-center medium-text-left" id="item35816298">
                                            <div class="product-item__content">
                                                <a href="https://louis-vuitton.su/products/35816298" class="product-item__preview product-item__preview_250x190"><img src="//i.siteapi.org/A0Fc1EKZDsWCfKt0zdiM7mhtWvw=/0x33:435x421/fit-in/250x190/center/top/filters:fill(transparent):format(png)/cd2000cd7dfd450.s2.siteapi.org/img/roj1536uvgg4sgssssgg8o488o0kco" alt="Рюкзак Josh Damier Graphite Canvas" title="Рюкзак Josh Damier Graphite Canvas"><div class="show-for-large"></div>
                                                    <div class="product-item__button js-order-product cart-btn button button_for_product-card show-for-large js-cart-btn">
                                                        <div class="cart-btn__icon">
                                                            <!-- Generated by IcoMoon.io --><svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="512" height="512" viewbox="0 0 512 512"><g id="icomoon-ignore"></g><path d="M192 464c0 26.51-21.49 48-48 48s-48-21.49-48-48c0-26.51 21.49-48 48-48s48 21.49 48 48z"></path><path d="M512 464c0 26.51-21.49 48-48 48s-48-21.49-48-48c0-26.51 21.49-48 48-48s48 21.49 48 48z"></path><path d="M512 256v-192h-384c0-17.673-14.327-32-32-32h-96v32h64l24.037 206.027c-14.647 11.729-24.037 29.75-24.037 49.973 0 35.348 28.654 64 64 64h384v-32h-384c-17.673 0-32-14.327-32-32 0-0.109 0.007-0.218 0.008-0.328l415.992-63.672z"></path></svg>
                                                        </div>
                                                        <div class="cart-btn__text">В корзину</div>
                                                    </div></a><div class="product-item__content">
                                                    <div class="product-item__link"><a href="https://louis-vuitton.su/products/35816298">Рюкзак Josh Damier Graphite Canvas</a></div>
                                                    <div class="product-item__price -inline-group"><div class="product-item-price">16 000 руб.</div></div>
                                                    <div class="hide-for-large"></div>
                                                </div>
                                            </div>
                                            <div class="product-item__button cart-btn js-order-product button button_for_product-card hide-for-large js-cart-btn">
                                                <div class="cart-btn__icon">
                                                    <!-- Generated by IcoMoon.io --><svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="512" height="512" viewbox="0 0 512 512"><g id="icomoon-ignore"></g><path d="M192 464c0 26.51-21.49 48-48 48s-48-21.49-48-48c0-26.51 21.49-48 48-48s48 21.49 48 48z"></path><path d="M512 464c0 26.51-21.49 48-48 48s-48-21.49-48-48c0-26.51 21.49-48 48-48s48 21.49 48 48z"></path><path d="M512 256v-192h-384c0-17.673-14.327-32-32-32h-96v32h64l24.037 206.027c-14.647 11.729-24.037 29.75-24.037 49.973 0 35.348 28.654 64 64 64h384v-32h-384c-17.673 0-32-14.327-32-32 0-0.109 0.007-0.218 0.008-0.328l415.992-63.672z"></path></svg>
                                                </div>
                                                <div class="cart-btn__text">В корзину</div>
                                            </div>
                                        </div></div>
                                    <div class="catalog__product column"><div class="product-item product-item_250x190 product-item_cant-buy text-center medium-text-left" id="item"><div class="product-item__content">
                                                <a href="" class="product-item__preview product-item__preview_250x190"><div class="product-item__no-photo">
                                                        <svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" id="Layer_1" data-name="Layer 1" viewbox="0 0 80 98"><path fill="#ccc" fill-rule="evenodd" d="M94.95,101.74h0v-70h0A2,2,0,0,0,93,30H71V22a16,16,0,0,0-32,0v8H17a2,2,0,0,0-1.95,1.74h0v70h0A1.65,1.65,0,0,0,15,102a2,2,0,0,0,2,2H93a2,2,0,0,0,2-2A1.66,1.66,0,0,0,94.95,101.74ZM43,22a12,12,0,0,1,24,0v8H43V22ZM19,34H39v4.55a4,4,0,1,0,4,0V34H67v4.55a4,4,0,1,0,4,0V34H91v66H19V34Z" transform="translate(-15 -6)"></path></svg>
                                                    </div>
                                                    <div class="show-for-large"></div></a><div class="product-item__content">
                                                    <div class="product-item__link"><a href=""></a></div>
                                                    <div class="hide-for-large"></div>
                                                </div>
                                            </div></div></div>
                                    <div class="catalog__product column"><div class="product-item product-item_250x190 product-item_cant-buy text-center medium-text-left" id="item"><div class="product-item__content">
                                                <a href="" class="product-item__preview product-item__preview_250x190"><div class="product-item__no-photo">
                                                       <svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" id="Layer_1" data-name="Layer 1" viewbox="0 0 80 98"><path fill="#ccc" fill-rule="evenodd" d="M94.95,101.74h0v-70h0A2,2,0,0,0,93,30H71V22a16,16,0,0,0-32,0v8H17a2,2,0,0,0-1.95,1.74h0v70h0A1.65,1.65,0,0,0,15,102a2,2,0,0,0,2,2H93a2,2,0,0,0,2-2A1.66,1.66,0,0,0,94.95,101.74ZM43,22a12,12,0,0,1,24,0v8H43V22ZM19,34H39v4.55a4,4,0,1,0,4,0V34H67v4.55a4,4,0,1,0,4,0V34H91v66H19V34Z" transform="translate(-15 -6)"></path></svg>
                                                    </div>
                                                    <div class="show-for-large"></div></a><div class="product-item__content">
                                                    <div class="product-item__link"><a href=""></a></div>
                                                    <div class="hide-for-large"></div>
                                                </div>
                                            </div></div></div>
                                    <div class="catalog__product column"><div class="product-item product-item_250x190 product-item_cant-buy text-center medium-text-left" id="item"><div class="product-item__content">
                                                <a href="" class="product-item__preview product-item__preview_250x190"><div class="product-item__no-photo">
                                                        <svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" id="Layer_1" data-name="Layer 1" viewbox="0 0 80 98"><path fill="#ccc" fill-rule="evenodd" d="M94.95,101.74h0v-70h0A2,2,0,0,0,93,30H71V22a16,16,0,0,0-32,0v8H17a2,2,0,0,0-1.95,1.74h0v70h0A1.65,1.65,0,0,0,15,102a2,2,0,0,0,2,2H93a2,2,0,0,0,2-2A1.66,1.66,0,0,0,94.95,101.74ZM43,22a12,12,0,0,1,24,0v8H43V22ZM19,34H39v4.55a4,4,0,1,0,4,0V34H67v4.55a4,4,0,1,0,4,0V34H91v66H19V34Z" transform="translate(-15 -6)"></path></svg>
                                                    </div>
                                                    <div class="show-for-large"></div></a><div class="product-item__content">
                                                    <div class="product-item__link"><a href=""></a></div>
                                                    <div class="hide-for-large"></div>
                                                </div>
                                            </div></div></div>
                                    <div class="catalog__product column"><div class="product-item product-item_250x190 product-item_cant-buy text-center medium-text-left" id="item"><div class="product-item__content">
                                                <a href="" class="product-item__preview product-item__preview_250x190"><div class="product-item__no-photo">
                                                        <svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" id="Layer_1" data-name="Layer 1" viewbox="0 0 80 98"><path fill="#ccc" fill-rule="evenodd" d="M94.95,101.74h0v-70h0A2,2,0,0,0,93,30H71V22a16,16,0,0,0-32,0v8H17a2,2,0,0,0-1.95,1.74h0v70h0A1.65,1.65,0,0,0,15,102a2,2,0,0,0,2,2H93a2,2,0,0,0,2-2A1.66,1.66,0,0,0,94.95,101.74ZM43,22a12,12,0,0,1,24,0v8H43V22ZM19,34H39v4.55a4,4,0,1,0,4,0V34H67v4.55a4,4,0,1,0,4,0V34H91v66H19V34Z" transform="translate(-15 -6)"></path></svg>
                                                    </div>
                                                    <div class="show-for-large"></div></a><div class="product-item__content">
                                                    <div class="product-item__link"><a href=""></a></div>
                                                    <div class="hide-for-large"></div>
                                                </div>
                                            </div></div></div>
                                    <div class="catalog__product column"><div class="product-item product-item_250x190 product-item_cant-buy text-center medium-text-left" id="item"><div class="product-item__content">
                                                <a href="" class="product-item__preview product-item__preview_250x190"><div class="product-item__no-photo">
                                                       <svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" id="Layer_1" data-name="Layer 1" viewbox="0 0 80 98"><path fill="#ccc" fill-rule="evenodd" d="M94.95,101.74h0v-70h0A2,2,0,0,0,93,30H71V22a16,16,0,0,0-32,0v8H17a2,2,0,0,0-1.95,1.74h0v70h0A1.65,1.65,0,0,0,15,102a2,2,0,0,0,2,2H93a2,2,0,0,0,2-2A1.66,1.66,0,0,0,94.95,101.74ZM43,22a12,12,0,0,1,24,0v8H43V22ZM19,34H39v4.55a4,4,0,1,0,4,0V34H67v4.55a4,4,0,1,0,4,0V34H91v66H19V34Z" transform="translate(-15 -6)"></path></svg>
                                                    </div>
                                                    <div class="show-for-large"></div></a><div class="product-item__content">
                                                    <div class="product-item__link"><a href=""></a></div>
                                                    <div class="hide-for-large"></div>
                                                </div>
                                            </div></div></div>
                                    <div class="catalog__product column"><div class="product-item product-item_250x190 product-item_cant-buy text-center medium-text-left" id="item"><div class="product-item__content">
                                                <a href="" class="product-item__preview product-item__preview_250x190"><div class="product-item__no-photo">
                                                       <svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" id="Layer_1" data-name="Layer 1" viewbox="0 0 80 98"><path fill="#ccc" fill-rule="evenodd" d="M94.95,101.74h0v-70h0A2,2,0,0,0,93,30H71V22a16,16,0,0,0-32,0v8H17a2,2,0,0,0-1.95,1.74h0v70h0A1.65,1.65,0,0,0,15,102a2,2,0,0,0,2,2H93a2,2,0,0,0,2-2A1.66,1.66,0,0,0,94.95,101.74ZM43,22a12,12,0,0,1,24,0v8H43V22ZM19,34H39v4.55a4,4,0,1,0,4,0V34H67v4.55a4,4,0,1,0,4,0V34H91v66H19V34Z" transform="translate(-15 -6)"></path></svg>
                                                    </div>
                                                    <div class="show-for-large"></div></a><div class="product-item__content">
                                                    <div class="product-item__link"><a href=""></a></div>
                                                    <div class="hide-for-large"></div>
                                                </div>
                                            </div></div></div>
                                    <div class="catalog__product column"><div class="product-item product-item_250x190 product-item_cant-buy text-center medium-text-left" id="item"><div class="product-item__content">
                                                <a href="" class="product-item__preview product-item__preview_250x190"><div class="product-item__no-photo">
                                                        <svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" id="Layer_1" data-name="Layer 1" viewbox="0 0 80 98"><path fill="#ccc" fill-rule="evenodd" d="M94.95,101.74h0v-70h0A2,2,0,0,0,93,30H71V22a16,16,0,0,0-32,0v8H17a2,2,0,0,0-1.95,1.74h0v70h0A1.65,1.65,0,0,0,15,102a2,2,0,0,0,2,2H93a2,2,0,0,0,2-2A1.66,1.66,0,0,0,94.95,101.74ZM43,22a12,12,0,0,1,24,0v8H43V22ZM19,34H39v4.55a4,4,0,1,0,4,0V34H67v4.55a4,4,0,1,0,4,0V34H91v66H19V34Z" transform="translate(-15 -6)"></path></svg>
                                                    </div>
                                                    <div class="show-for-large"></div></a><div class="product-item__content">
                                                    <div class="product-item__link"><a href=""></a></div>
                                                    <div class="hide-for-large"></div>
                                                </div>
                                            </div></div></div>
                                    <div class="catalog__product column"><div class="product-item product-item_250x190 product-item_cant-buy text-center medium-text-left" id="item"><div class="product-item__content">
                                                <a href="" class="product-item__preview product-item__preview_250x190"><div class="product-item__no-photo">
                                                        <svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" id="Layer_1" data-name="Layer 1" viewbox="0 0 80 98"><path fill="#ccc" fill-rule="evenodd" d="M94.95,101.74h0v-70h0A2,2,0,0,0,93,30H71V22a16,16,0,0,0-32,0v8H17a2,2,0,0,0-1.95,1.74h0v70h0A1.65,1.65,0,0,0,15,102a2,2,0,0,0,2,2H93a2,2,0,0,0,2-2A1.66,1.66,0,0,0,94.95,101.74ZM43,22a12,12,0,0,1,24,0v8H43V22ZM19,34H39v4.55a4,4,0,1,0,4,0V34H67v4.55a4,4,0,1,0,4,0V34H91v66H19V34Z" transform="translate(-15 -6)"></path></svg>
                                                    </div>
                                                    <div class="show-for-large"></div></a><div class="product-item__content">
                                                    <div class="product-item__link"><a href=""></a></div>
                                                    <div class="hide-for-large"></div>
                                                </div>
                                            </div></div></div>
                                    <div class="catalog__product column"><div class="product-item product-item_250x190 product-item_cant-buy text-center medium-text-left" id="item"><div class="product-item__content">
                                                <a href="" class="product-item__preview product-item__preview_250x190"><div class="product-item__no-photo">
                                                       <svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" id="Layer_1" data-name="Layer 1" viewbox="0 0 80 98"><path fill="#ccc" fill-rule="evenodd" d="M94.95,101.74h0v-70h0A2,2,0,0,0,93,30H71V22a16,16,0,0,0-32,0v8H17a2,2,0,0,0-1.95,1.74h0v70h0A1.65,1.65,0,0,0,15,102a2,2,0,0,0,2,2H93a2,2,0,0,0,2-2A1.66,1.66,0,0,0,94.95,101.74ZM43,22a12,12,0,0,1,24,0v8H43V22ZM19,34H39v4.55a4,4,0,1,0,4,0V34H67v4.55a4,4,0,1,0,4,0V34H91v66H19V34Z" transform="translate(-15 -6)"></path></svg>
                                                    </div>
                                                    <div class="show-for-large"></div></a><div class="product-item__content">
                                                    <div class="product-item__link"><a href=""></a></div>
                                                    <div class="hide-for-large"></div>
                                                </div>
                                            </div></div></div>
                                    <div class="catalog__product column"><div class="product-item product-item_250x190 product-item_cant-buy text-center medium-text-left" id="item"><div class="product-item__content">
                                                <a href="" class="product-item__preview product-item__preview_250x190"><div class="product-item__no-photo">
                                                        <svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" id="Layer_1" data-name="Layer 1" viewbox="0 0 80 98"><path fill="#ccc" fill-rule="evenodd" d="M94.95,101.74h0v-70h0A2,2,0,0,0,93,30H71V22a16,16,0,0,0-32,0v8H17a2,2,0,0,0-1.95,1.74h0v70h0A1.65,1.65,0,0,0,15,102a2,2,0,0,0,2,2H93a2,2,0,0,0,2-2A1.66,1.66,0,0,0,94.95,101.74ZM43,22a12,12,0,0,1,24,0v8H43V22ZM19,34H39v4.55a4,4,0,1,0,4,0V34H67v4.55a4,4,0,1,0,4,0V34H91v66H19V34Z" transform="translate(-15 -6)"></path></svg>
                                                    </div>
                                                    <div class="show-for-large"></div></a><div class="product-item__content">
                                                    <div class="product-item__link"><a href=""></a></div>
                                                    <div class="hide-for-large"></div>
                                                </div>
                                            </div></div></div>
                                    <div class="catalog__product column"><div class="product-item product-item_250x190 product-item_cant-buy text-center medium-text-left" id="item"><div class="product-item__content">
                                                <a href="" class="product-item__preview product-item__preview_250x190"><div class="product-item__no-photo">
                                                        <svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" id="Layer_1" data-name="Layer 1" viewbox="0 0 80 98"><path fill="#ccc" fill-rule="evenodd" d="M94.95,101.74h0v-70h0A2,2,0,0,0,93,30H71V22a16,16,0,0,0-32,0v8H17a2,2,0,0,0-1.95,1.74h0v70h0A1.65,1.65,0,0,0,15,102a2,2,0,0,0,2,2H93a2,2,0,0,0,2-2A1.66,1.66,0,0,0,94.95,101.74ZM43,22a12,12,0,0,1,24,0v8H43V22ZM19,34H39v4.55a4,4,0,1,0,4,0V34H67v4.55a4,4,0,1,0,4,0V34H91v66H19V34Z" transform="translate(-15 -6)"></path></svg>
                                                    </div>
                                                    <div class="show-for-large"></div></a><div class="product-item__content">
                                                    <div class="product-item__link"><a href=""></a></div>
                                                    <div class="hide-for-large"></div>
                                                </div>
                                            </div></div></div>
                                    <div class="catalog__product column"><div class="product-item product-item_250x190 product-item_cant-buy text-center medium-text-left" id="item"><div class="product-item__content">
                                                <a href="" class="product-item__preview product-item__preview_250x190"><div class="product-item__no-photo">
                                                        <svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" id="Layer_1" data-name="Layer 1" viewbox="0 0 80 98"><path fill="#ccc" fill-rule="evenodd" d="M94.95,101.74h0v-70h0A2,2,0,0,0,93,30H71V22a16,16,0,0,0-32,0v8H17a2,2,0,0,0-1.95,1.74h0v70h0A1.65,1.65,0,0,0,15,102a2,2,0,0,0,2,2H93a2,2,0,0,0,2-2A1.66,1.66,0,0,0,94.95,101.74ZM43,22a12,12,0,0,1,24,0v8H43V22ZM19,34H39v4.55a4,4,0,1,0,4,0V34H67v4.55a4,4,0,1,0,4,0V34H91v66H19V34Z" transform="translate(-15 -6)"></path></svg>
                                                    </div>
                                                    <div class="show-for-large"></div></a><div class="product-item__content">
                                                    <div class="product-item__link"><a href=""></a></div>
                                                    <div class="hide-for-large"></div>
                                                </div>
                                            </div></div></div>
                                    <div class="catalog__product column"><div class="product-item product-item_250x190 product-item_cant-buy text-center medium-text-left" id="item"><div class="product-item__content">
                                                <a href="" class="product-item__preview product-item__preview_250x190"><div class="product-item__no-photo">
                                                        <svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" id="Layer_1" data-name="Layer 1" viewbox="0 0 80 98"><path fill="#ccc" fill-rule="evenodd" d="M94.95,101.74h0v-70h0A2,2,0,0,0,93,30H71V22a16,16,0,0,0-32,0v8H17a2,2,0,0,0-1.95,1.74h0v70h0A1.65,1.65,0,0,0,15,102a2,2,0,0,0,2,2H93a2,2,0,0,0,2-2A1.66,1.66,0,0,0,94.95,101.74ZM43,22a12,12,0,0,1,24,0v8H43V22ZM19,34H39v4.55a4,4,0,1,0,4,0V34H67v4.55a4,4,0,1,0,4,0V34H91v66H19V34Z" transform="translate(-15 -6)"></path></svg>
                                                    </div>
                                                    <div class="show-for-large"></div></a><div class="product-item__content">
                                                    <div class="product-item__link"><a href=""></a></div>
                                                    <div class="hide-for-large"></div>
                                                </div>
                                            </div></div></div>
                                    <div class="catalog__product column"><div class="product-item product-item_250x190 product-item_cant-buy text-center medium-text-left" id="item"><div class="product-item__content">
                                                <a href="" class="product-item__preview product-item__preview_250x190"><div class="product-item__no-photo">
                                                        <svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" id="Layer_1" data-name="Layer 1" viewbox="0 0 80 98"><path fill="#ccc" fill-rule="evenodd" d="M94.95,101.74h0v-70h0A2,2,0,0,0,93,30H71V22a16,16,0,0,0-32,0v8H17a2,2,0,0,0-1.95,1.74h0v70h0A1.65,1.65,0,0,0,15,102a2,2,0,0,0,2,2H93a2,2,0,0,0,2-2A1.66,1.66,0,0,0,94.95,101.74ZM43,22a12,12,0,0,1,24,0v8H43V22ZM19,34H39v4.55a4,4,0,1,0,4,0V34H67v4.55a4,4,0,1,0,4,0V34H91v66H19V34Z" transform="translate(-15 -6)"></path></svg>
                                                    </div>
                                                    <div class="show-for-large"></div></a><div class="product-item__content">
                                                    <div class="product-item__link"><a href=""></a></div>
                                                    <div class="hide-for-large"></div>
                                                </div>
                                            </div></div></div>
                                    <div class="catalog__product column"><div class="product-item product-item_250x190 product-item_cant-buy text-center medium-text-left" id="item"><div class="product-item__content">
                                                <a href="" class="product-item__preview product-item__preview_250x190"><div class="product-item__no-photo">
                                                       <svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" id="Layer_1" data-name="Layer 1" viewbox="0 0 80 98"><path fill="#ccc" fill-rule="evenodd" d="M94.95,101.74h0v-70h0A2,2,0,0,0,93,30H71V22a16,16,0,0,0-32,0v8H17a2,2,0,0,0-1.95,1.74h0v70h0A1.65,1.65,0,0,0,15,102a2,2,0,0,0,2,2H93a2,2,0,0,0,2-2A1.66,1.66,0,0,0,94.95,101.74ZM43,22a12,12,0,0,1,24,0v8H43V22ZM19,34H39v4.55a4,4,0,1,0,4,0V34H67v4.55a4,4,0,1,0,4,0V34H91v66H19V34Z" transform="translate(-15 -6)"></path></svg>
                                                    </div>
                                                    <div class="show-for-large"></div></a><div class="product-item__content">
                                                    <div class="product-item__link"><a href=""></a></div>
                                                    <div class="hide-for-large"></div>
                                                </div>
                                            </div></div></div>
                                    <div class="catalog__product column"><div class="product-item product-item_250x190 product-item_cant-buy text-center medium-text-left" id="item"><div class="product-item__content">
                                                <a href="" class="product-item__preview product-item__preview_250x190"><div class="product-item__no-photo">
                                                       <svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" id="Layer_1" data-name="Layer 1" viewbox="0 0 80 98"><path fill="#ccc" fill-rule="evenodd" d="M94.95,101.74h0v-70h0A2,2,0,0,0,93,30H71V22a16,16,0,0,0-32,0v8H17a2,2,0,0,0-1.95,1.74h0v70h0A1.65,1.65,0,0,0,15,102a2,2,0,0,0,2,2H93a2,2,0,0,0,2-2A1.66,1.66,0,0,0,94.95,101.74ZM43,22a12,12,0,0,1,24,0v8H43V22ZM19,34H39v4.55a4,4,0,1,0,4,0V34H67v4.55a4,4,0,1,0,4,0V34H91v66H19V34Z" transform="translate(-15 -6)"></path></svg>
                                                    </div>
                                                    <div class="show-for-large"></div></a><div class="product-item__content">
                                                    <div class="product-item__link"><a href=""></a></div>
                                                    <div class="hide-for-large"></div>
                                                </div>
                                            </div></div></div>
                                    <div class="catalog__product column"><div class="product-item product-item_250x190 product-item_cant-buy text-center medium-text-left" id="item"><div class="product-item__content">
                                                <a href="" class="product-item__preview product-item__preview_250x190"><div class="product-item__no-photo">
                                                        <svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" id="Layer_1" data-name="Layer 1" viewbox="0 0 80 98"><path fill="#ccc" fill-rule="evenodd" d="M94.95,101.74h0v-70h0A2,2,0,0,0,93,30H71V22a16,16,0,0,0-32,0v8H17a2,2,0,0,0-1.95,1.74h0v70h0A1.65,1.65,0,0,0,15,102a2,2,0,0,0,2,2H93a2,2,0,0,0,2-2A1.66,1.66,0,0,0,94.95,101.74ZM43,22a12,12,0,0,1,24,0v8H43V22ZM19,34H39v4.55a4,4,0,1,0,4,0V34H67v4.55a4,4,0,1,0,4,0V34H91v66H19V34Z" transform="translate(-15 -6)"></path></svg>
                                                    </div>
                                                    <div class="show-for-large"></div></a><div class="product-item__content">
                                                    <div class="product-item__link"><a href=""></a></div>
                                                    <div class="hide-for-large"></div>
                                                </div>
                                            </div></div></div>
                                    <div class="catalog__product column"><div class="product-item product-item_250x190 product-item_cant-buy text-center medium-text-left" id="item"><div class="product-item__content">
                                                <a href="" class="product-item__preview product-item__preview_250x190"><div class="product-item__no-photo">
                                                        <svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" id="Layer_1" data-name="Layer 1" viewbox="0 0 80 98"><path fill="#ccc" fill-rule="evenodd" d="M94.95,101.74h0v-70h0A2,2,0,0,0,93,30H71V22a16,16,0,0,0-32,0v8H17a2,2,0,0,0-1.95,1.74h0v70h0A1.65,1.65,0,0,0,15,102a2,2,0,0,0,2,2H93a2,2,0,0,0,2-2A1.66,1.66,0,0,0,94.95,101.74ZM43,22a12,12,0,0,1,24,0v8H43V22ZM19,34H39v4.55a4,4,0,1,0,4,0V34H67v4.55a4,4,0,1,0,4,0V34H91v66H19V34Z" transform="translate(-15 -6)"></path></svg>
                                                    </div>
                                                    <div class="show-for-large"></div></a><div class="product-item__content">
                                                    <div class="product-item__link"><a href=""></a></div>
                                                    <div class="hide-for-large"></div>
                                                </div>
                                            </div></div></div>
                                    <div class="catalog__product column"><div class="product-item product-item_250x190 product-item_cant-buy text-center medium-text-left" id="item"><div class="product-item__content">
                                                <a href="" class="product-item__preview product-item__preview_250x190"><div class="product-item__no-photo">
                                                        <svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" id="Layer_1" data-name="Layer 1" viewbox="0 0 80 98"><path fill="#ccc" fill-rule="evenodd" d="M94.95,101.74h0v-70h0A2,2,0,0,0,93,30H71V22a16,16,0,0,0-32,0v8H17a2,2,0,0,0-1.95,1.74h0v70h0A1.65,1.65,0,0,0,15,102a2,2,0,0,0,2,2H93a2,2,0,0,0,2-2A1.66,1.66,0,0,0,94.95,101.74ZM43,22a12,12,0,0,1,24,0v8H43V22ZM19,34H39v4.55a4,4,0,1,0,4,0V34H67v4.55a4,4,0,1,0,4,0V34H91v66H19V34Z" transform="translate(-15 -6)"></path></svg>
                                                    </div>
                                                    <div class="show-for-large"></div></a><div class="product-item__content">
                                                    <div class="product-item__link"><a href=""></a></div>
                                                    <div class="hide-for-large"></div>
                                                </div>
                                            </div></div></div></article>
                                <div class="text-center catalog__pagination">
                                    <div class="pagination pagination_min-width">
                                        <div class="pagination__arrow_left pagination__arrow_disabled">
                                            <svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="768" height="768" viewbox="0 0 768 768"><path d="M493.5 514.5l-45 45-192-192 192-192 45 45-147 147z"></path></svg>                </div>
                                        <div class="pagination__pages">
                                            <div class="pagination__item pagination__item_active">
                                                1
                                            </div>
                                            <a class="pagination__item " href="https://louis-vuitton.su/products/search?text=&amp;sort=&amp;balance=&amp;categoryId=&amp;min_cost=&amp;max_cost=&amp;page=2">
                                                2
                                            </a>
                                            <a class="pagination__item " href="https://louis-vuitton.su/products/search?text=&amp;sort=&amp;balance=&amp;categoryId=&amp;min_cost=&amp;max_cost=&amp;page=3">
                                                3
                                            </a>
                                            <a class="pagination__item " href="https://louis-vuitton.su/products/search?text=&amp;sort=&amp;balance=&amp;categoryId=&amp;min_cost=&amp;max_cost=&amp;page=4">
                                                4
                                            </a>
                                            <a class="pagination__item " href="https://louis-vuitton.su/products/search?text=&amp;sort=&amp;balance=&amp;categoryId=&amp;min_cost=&amp;max_cost=&amp;page=5">
                                                5
                                            </a>
                                            <a class="pagination__item hide-for-small-only" href="https://louis-vuitton.su/products/search?text=&amp;sort=&amp;balance=&amp;categoryId=&amp;min_cost=&amp;max_cost=&amp;page=6">
                                                6
                                            </a>
                                            <div class="pagination__item pagination__item_three-dots">
                                                ...
                                            </div>
                                            <a class="pagination__item" href="https://louis-vuitton.su/products/search?text=&amp;sort=&amp;balance=&amp;categoryId=&amp;min_cost=&amp;max_cost=&amp;page=16">
                                                16
                                            </a>
                                        </div>
                                        <a class="pagination__arrow_right" href="https://louis-vuitton.su/products/search?text=&amp;sort=&amp;balance=&amp;categoryId=&amp;min_cost=&amp;max_cost=&amp;page=2">
                                           <svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="768" height="768" viewbox="0 0 768 768"><path d="M274.5 523.5l147-147-147-147 45-45 192 192-192 192z"></path></svg>                </a>
                                    </div>

                                </div>






                            </div>
                        </div>
                    </div>
                </section>

                <script type="text/javascript">
                    if (typeof gtag != 'undefined') {
                        gtag('event', 'view_item_list', {"items":[{"id":"3","name":"\u0420\u044e\u043a\u0437\u0430\u043a Josh Damier Graphite Canvas","list_name":"search results","list_position":1,"price":"16000","category":"\u0420\u044e\u043a\u0437\u0430\u043a\u0438 Louis Vuitton"},{"id":null,"name":null,"list_name":"search results","list_position":2,"price":null},{"id":null,"name":null,"list_name":"search results","list_position":3,"price":null},{"id":null,"name":null,"list_name":"search results","list_position":4,"price":null},{"id":null,"name":null,"list_name":"search results","list_position":5,"price":null},{"id":null,"name":null,"list_name":"search results","list_position":6,"price":null},{"id":null,"name":null,"list_name":"search results","list_position":7,"price":null},{"id":null,"name":null,"list_name":"search results","list_position":8,"price":null},{"id":null,"name":null,"list_name":"search results","list_position":9,"price":null},{"id":null,"name":null,"list_name":"search results","list_position":10,"price":null},{"id":null,"name":null,"list_name":"search results","list_position":11,"price":null},{"id":null,"name":null,"list_name":"search results","list_position":12,"price":null},{"id":null,"name":null,"list_name":"search results","list_position":13,"price":null},{"id":null,"name":null,"list_name":"search results","list_position":14,"price":null},{"id":null,"name":null,"list_name":"search results","list_position":15,"price":null},{"id":null,"name":null,"list_name":"search results","list_position":16,"price":null},{"id":null,"name":null,"list_name":"search results","list_position":17,"price":null},{"id":null,"name":null,"list_name":"search results","list_position":18,"price":null},{"id":null,"name":null,"list_name":"search results","list_position":19,"price":null},{"id":null,"name":null,"list_name":"search results","list_position":20,"price":null}]});
                    }
                </script>


                <div class="widget__content widget__content_filled">
                    <div class="row">
                        <div data-ng-if="$ctrl.loaded" class="widget__view small-12 column" data-ui-view="catalog-view"></div>
                    </div>
                </div>

            </section>

        </div>
    </section>
</div>



<?php

get_footer();
?>
